apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nbpcloud-api.fullname" . }}-dbstring
  labels:
    {{- include "nbpcloud-api.labels" . | nindent 4 }}
    version: {{ .Values.version }}
  resourceVersion: {{ .Values.secretfile.version | quote }}
type: Opaque
data:
  dbstring: {{ .Files.Get ".dbstring" | b64enc }}
  