apiVersion: v1
kind: Secret
data:
  .dockerconfigjson: {{ .Files.Get ".dockersecret" | b64enc }}

metadata:
  name: {{ include "nbpcloud-api.fullname" . }}
  labels:
    {{- include "nbpcloud-api.labels" . | nindent 4 }}
    version: {{ .Values.version }}
  resourceVersion: {{ .Values.secretfile.version | quote }}
type: {{ .Values.secretfile.type }}
