- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
      - ./templates/var.yaml
  tasks:
  
    - name: Setting Kube Context
      shell: kubectl config use-context {{ app.kubeContext }}

    - name: Creating ingress resource from templates
      template:
        src: ingress.yaml.j2
        dest: templates/ingress.yaml
      
    - name: Deleting the old ingress resource
      shell:  "kubectl delete -f templates/ingress.yaml"
      when:  ingress.delete  == true
      ignore_errors: yes
        
    - name: Creating the ingress resource
      shell:  "kubectl apply -f templates/ingress.yaml"
      when:  ingress.apply  == true

    - name: Cleaning the generated files  
      file:
        path:  templates/ingress.yaml
        state: absent
      when:  ingress.clean == true
      
      